apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentracing-pod-annotator
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opentracing-pod-annotator
rules:
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - list
    - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opentracing-pod-annotator
  namespace: default
subjects:
- kind: ServiceAccount
  name: opentracing-pod-annotator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opentracing-pod-annotator
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentracing-pod-annotator
  namespace: default
  labels:
    app: opentracing-pod-annotator
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: opentracing-pod-annotator
  template:
    metadata:
      labels:
        app: opentracing-pod-annotator
    spec:
      serviceAccountName: opentracing-pod-annotator
      containers:
        - name: opentracing-pod-annotator
          image: quay.io/skedulo/opentracing-pod-annotator:v0.1-16-g3928297
          imagePullPolicy: IfNotPresent
          args:
            - --log-level=debug
            - --namespaces=default
---
apiVersion: v1
kind: Service
metadata:
  name: opentracing-pod-annotator
  namespace: default
  labels:
    app: opentracing-pod-annotator
spec:
  selector:
    app: opentracing-pod-annotator
  ports:
    - name: http
      port: 8080
  type: NodePort
